<?php
/**
 * Copyright © Rob Aimes - https://aimes.dev
 */

/**
 * Product media data template
 *
 * @var $block \Aimes\Notorama\Block\Product\Gallery
 * @var $galleryViewModel \Aimes\Notorama\viewModel\Product\Gallery
 */
$galleryViewModel = $block->getGalleryViewModel();
$jsConfig = $galleryViewModel->getJsConfig($block->getGalleryImagesJson());
?>
<div id="notorama-gallery" class="notorama loading <?= $galleryViewModel->getIsVertical() ? 'vertical' : '' ?>" data-mage-init='{"notorama": <?= $jsConfig ?>}'>
    <div id="gallery-placeholder" class="gallery-placeholder _block-content-loading" data-gallery-role="gallery-placeholder">
        <div class="notorama-view-wrapper">
            <div id="notorama-viewer" class="notorama-gallery-view">
                <?php if ($galleryViewModel->isViewerArrowsEnabled()): ?>
                <button type="button" class="slick-arrow slick-prev" aria-label="<?= $block->escapeHtml(__('Previous')) ?>">
                    <svg viewBox="0 0 32 32" width="32" height="32">
                        <path d="M 19.41,20.09 14.83,15.5 19.41,10.91 18,9.5 l -6,6 6,6 z" fill="currentColor"></path>
                    </svg>
                </button>
                <?php endif ?>
                <div class="placeholder">
                    <img class="notorama-placeholder-img" src="<?= $block->getPlaceholderImage() ?>" alt="<?= $block->getPlaceholderImageCaption() ?>" />
                </div>
                <?php if ($galleryViewModel->isViewerArrowsEnabled()): ?>
                <button type="button" class="slick-arrow slick-next" aria-label="<?= $block->escapeHtml(__('Next')) ?>">
                    <svg viewBox="0 0 32 32" width="32" height="32">
                        <path d="m 12.59,20.34 4.58,-4.59 -4.58,-4.59 1.41,-1.41 6,6 -6,6 z" fill="currentColor"></path>
                    </svg>
                </button>
                <?php endif ?>
            </div>
            <?php if ($galleryViewModel->isZoomEnabled()): ?>
            <div class="notorama-zoom <?= $galleryViewModel->getZoomPosition() ?>"></div>
            <?php endif ?>
            <div id="notorama-dots">
                <ul class="slick-dots">
                    <?php for ($i=0; $i < count($block->getGalleryImages()); $i++): ?>
                        <li class="<?= $i==0 ? 'slick-active"' : '' ?>">
                            <button type="button"><?= $i ?></button>
                        </li>
                    <?php endfor ?>
                </ul>
            </div>
        </div>
        <div id="notorama-carousel" class="notorama-carousel">
            <?php if ($galleryViewModel->isCarouselArrowsEnabled()): ?>
            <button type="button" class="slick-arrow slick-prev" aria-label="<?= $block->escapeHtml(__('Previous')) ?>">
                <svg viewBox="0 0 32 32" width="32" height="32">
                    <path d="M 19.41,20.09 14.83,15.5 19.41,10.91 18,9.5 l -6,6 6,6 z" fill="currentColor"></path>
                </svg>
            </button>
            <?php endif ?>
            <div class="placeholder">
                <?php foreach ($block->getPlaceholderGalleryImages() as $i => $image): ?>
                <div class="notorama-placeholder-thumb <?= $i==0 ? 'slick-current"' : '' ?>">
                    <img src="<?= $image->getData('small_image_url') ?>" alt="<?= $image->getData('label') ?>" />
                </div>
                <?php endforeach ?>
            </div>
            <?php if ($galleryViewModel->isCarouselArrowsEnabled()): ?>
            <button type="button" class="slick-arrow slick-next" aria-label="<?= $block->escapeHtml(__('Next')) ?>">
                <svg viewBox="0 0 32 32" width="32" height="32">
                    <path d="m 12.59,20.34 4.58,-4.59 -4.58,-4.59 1.41,-1.41 6,6 -6,6 z" fill="currentColor"></path>
                </svg>
            </button>
            <?php endif ?>
        </div>
    </div>
</div>
